# Generated by Django 5.1.15 on 2026-08-25 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('customers', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('CUSTOMER_PAYMENT', 'Customer Payment / Khata Inflow'), ('SUPPLIER_PAYMENT', 'Supplier Payment / Outflow')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (₹)')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI (GPay / PhonePe / Paytm)'), ('CARD', 'Card'), ('BANK', 'Bank Transfer / NEFT'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Txn Ref / UTR / Receipt No.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.purchase')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.sale')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
