# Generated by Django 5.1.15 on 2026-08-25 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Business/Shop Name')),
                ('owner_name', models.CharField(max_length=150, verbose_name='Owner Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Shop Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Maharashtra', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, max_length=25, null=True, verbose_name='GSTIN Number (Optional)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10, verbose_name='Invoice Prefix')),
                ('next_invoice_number', models.PositiveIntegerField(default=1001)),
                ('invoice_footer', models.TextField(default='Thank you for your business! Goods once sold will be covered under manufacturer warranty. Visit again.', verbose_name='Invoice Terms & Footer')),
                ('plan_tier', models.CharField(choices=[('FREE', 'Free Starter (₹0/mo)'), ('PRO', 'Pro Merchant (₹199/mo)'), ('BUSINESS', 'Business Ultra (₹499/mo)')], default='FREE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
