# Generated by Django 6.1.1 on 2026-09-04 08:29

import businesses.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='subscription_end_date',
            field=models.DateField(default=businesses.models.get_default_subscription_end),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='invoice_footer',
            field=models.TextField(default='Thank you for your business! Goods once sold are covered under manufacturer warranty. Visit again.', verbose_name='Invoice Terms & Footer'),
        ),
        migrations.AlterField(
            model_name='business',
            name='invoice_prefix',
            field=models.CharField(default='SZ-', max_length=10, verbose_name='Invoice Prefix'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Shop / Business Name'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Mobile / WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='business',
            name='plan_tier',
            field=models.CharField(default='SHOPZEN_PREMIUM', max_length=30),
        ),
    ]
