# Generated by Django 6.1.1 on 2026-09-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Shop Owner'), ('STAFF', 'Staff Member'), ('SHOPZEN_ADMIN', 'ShopZen Admin')], default='OWNER', max_length=20),
        ),
    ]
